package com.confusinguser.confusingaddons.utils.bazaar;

import java.util.HashMap;
import java.util.Map;

public abstract class Constants {

    public static final Map<String, String> apiNamesToUserFriendyNames = new HashMap<>();
    static {
        apiNamesToUserFriendyNames.put("LOG", "Oak Wood");
        apiNamesToUserFriendyNames.put("LOG:1", "Spruce Wood");
        apiNamesToUserFriendyNames.put("LOG:2", "Brich Wood");
        apiNamesToUserFriendyNames.put("LOG:3", "Jungle Wood");
        apiNamesToUserFriendyNames.put("LOG_2", "Acacia Wood");
        apiNamesToUserFriendyNames.put("LOG_2:1", "Dark Oak Wood");
        apiNamesToUserFriendyNames.put("RAW_FISH:1", "Raw Salmon");
        apiNamesToUserFriendyNames.put("RAW_FISH:2", "Clownfish");
        apiNamesToUserFriendyNames.put("RAW_FISH:3", "Pufferfish");
        apiNamesToUserFriendyNames.put("POTATO_ITEM", "Potato");
        apiNamesToUserFriendyNames.put("CARROT_ITEM", "Carrot");
        apiNamesToUserFriendyNames.put("RABBIT", "Raw Rabbit");
        apiNamesToUserFriendyNames.put("ENCHANTED_RABBIT", "Enchanted Raw Rabbit");
        apiNamesToUserFriendyNames.put("HUGE_MUSHROOM_1", "Brown Mushroom Block");
        apiNamesToUserFriendyNames.put("HUGE_MUSHROOM_2", "Red Mushroom Block");
        apiNamesToUserFriendyNames.put("ENCHANTED_HUGE_MUSHROOM_1", "Enchanted Brown Mushroom Block");
        apiNamesToUserFriendyNames.put("ENCHANTED_HUGE_MUSHROOM_2", "Enchanted Red Mushroom Block");
        apiNamesToUserFriendyNames.put("NETHER_STALK", "Nether Wart");
        apiNamesToUserFriendyNames.put("ENCHANTED_NETHER_STALK", "Enchanted Nether Wart");
        apiNamesToUserFriendyNames.put("SNOW_BALL", "Snowball");
        apiNamesToUserFriendyNames.put("CLAY_BALL", "Clay");
        apiNamesToUserFriendyNames.put("SULPHUR", "Gunpowder");
    }

    public static final Map<String, Double> npcSellPrices = new HashMap<>();
    static {
        npcSellPrices.put("WHEAT", 1d);
        npcSellPrices.put("ENCHANTED_BREAD", 60d);
        npcSellPrices.put("HAY_BLOCK", 9d);
        npcSellPrices.put("ENCHANTED_HAY_BLOCK", 1300d);
        npcSellPrices.put("CARROT_ITEM", 1d);
        npcSellPrices.put("ENCHANTED_CARROT", 160d);
        npcSellPrices.put("ENCHANTED_CARROT_STICK", 10240d);
        npcSellPrices.put("ENCHANTED_GOLDEN_CARROT", 20608d);
        npcSellPrices.put("POTATO_ITEM", 1d);
        npcSellPrices.put("ENCHANTED_POTATO", 160d);
        npcSellPrices.put("ENCHANTED_BAKED_POTATO", 25600d);
        npcSellPrices.put("PUMPKIN", 4d);
        npcSellPrices.put("ENCHANTED_PUMPKIN", 640d);
        npcSellPrices.put("MELON", 0.5d);
        npcSellPrices.put("ENCHANTED_MELON", 160d);
        npcSellPrices.put("ENCHANTED_GLISTERING_MELON", 1000d);
        npcSellPrices.put("ENCHANTED_MELON_BLOCK", 25600d);
        npcSellPrices.put("SEEDS", 0.5d);
        npcSellPrices.put("ENCHANTED_SEEDS", 80d);
        npcSellPrices.put("RED_MUSHROOM", 4d);
        npcSellPrices.put("ENCHANTED_RED_MUSHROOM", 640d);
        npcSellPrices.put("HUGE_MUSHROOM_2", 4d);
        npcSellPrices.put("ENCHANTED_HUGE_MUSHROOM_2", 2300d);
        npcSellPrices.put("BROWN_MUSHROOM", 4d);
        npcSellPrices.put("ENCHANTED_BROWN_MUSHROOM", 640d);
        npcSellPrices.put("HUGE_MUSHROOM_1", 4d);
        npcSellPrices.put("ENCHANTED_HUGE_MUSHROOM_1", 2300d);
        npcSellPrices.put("INK_SACK:3", 3d);
        npcSellPrices.put("ENCHANTED_COCOA", 480d);
        npcSellPrices.put("ENCHANTED_COOKIE", 61500d);
        npcSellPrices.put("CACTUS", 1d);
        npcSellPrices.put("ENCHANTED_CACTUS_GREEN", 160d);
        npcSellPrices.put("ENCHANTED_CACTUS", 25600d);
        npcSellPrices.put("SUGAR_CANE", 2d);
        npcSellPrices.put("ENCHANTED_SUGAR", 320d);
        npcSellPrices.put("ENCHANTED_PAPER", 384d);
        npcSellPrices.put("ENCHANTED_SUGAR_CANE", 51200d);
        npcSellPrices.put("FEATHER", 3d);
        npcSellPrices.put("ENCHANTED_FEATHER", 480d);
        npcSellPrices.put("LEATHER", 3d);
        npcSellPrices.put("ENCHANTED_LEATHER", 1700d);
        npcSellPrices.put("RAW_BEEF", 4d);
        npcSellPrices.put("ENCHANTED_RAW_BEEF", 640d);
        npcSellPrices.put("PORK", 5d);
        npcSellPrices.put("ENCHANTED_PORK", 800d);
        npcSellPrices.put("ENCHANTED_GRILLED_PORK", 128000d);
        npcSellPrices.put("RAW_CHICKEN", 4d);
        npcSellPrices.put("ENCHANTED_RAW_CHICKEN", 640d);
        npcSellPrices.put("ENCHANTED_EGG", 432d);
        npcSellPrices.put("ENCHANTED_CAKE", 2700d);
        npcSellPrices.put("SUPER_EGG", 0d);
        npcSellPrices.put("MUTTON", 5d);
        npcSellPrices.put("ENCHANTED_MUTTON", 800d);
        npcSellPrices.put("ENCHANTED_COOKED_MUTTON", 128000d);
        npcSellPrices.put("RABBIT", 4d);
        npcSellPrices.put("ENCHANTED_RABBIT", 640d);
        npcSellPrices.put("RABBIT_FOOT", 5d);
        npcSellPrices.put("RABBIT_HIDE", 5d);
        npcSellPrices.put("ENCHANTED_RABBIT_FOOT", 800d);
        npcSellPrices.put("ENCHANTED_RABBIT_HIDE", 2880d);
        npcSellPrices.put("NETHER_STALK", 3d);
        npcSellPrices.put("ENCHANTED_NETHER_STALK", 480d);
        npcSellPrices.put("COBBLESTONE", 1d);
        npcSellPrices.put("ENCHANTED_COBBLESTONE", 160d);
        npcSellPrices.put("COAL", 2d);
        npcSellPrices.put("ENCHANTED_COAL", 320d);
        npcSellPrices.put("ENCHANTED_CHARCOAL", 320d);
        npcSellPrices.put("ENCHANTED_COAL_BLOCK", 51200d);
        npcSellPrices.put("IRON_INGOT", 3d);
        npcSellPrices.put("ENCHANTED_IRON", 480d);
        npcSellPrices.put("ENCHANTED_IRON_BLOCK", 76800d);
        npcSellPrices.put("GOLD_INGOT", 4d);
        npcSellPrices.put("ENCHANTED_GOLD", 640d);
        npcSellPrices.put("ENCHANTED_GOLD_BLOCK", 102400d);
        npcSellPrices.put("DIAMOND", 8d);
        npcSellPrices.put("ENCHANTED_DIAMOND", 1280d);
        npcSellPrices.put("ENCHANTED_DIAMOND_BLOCK", 204800d);
        npcSellPrices.put("INK_SACK:4", 1d);
        npcSellPrices.put("ENCHANTED_LAPIS_LAZULI", 160d);
        npcSellPrices.put("ENCHANTED_LAPIS_LAZULI_BLOCK", 25600d);
        npcSellPrices.put("EMERALD", 6d);
        npcSellPrices.put("ENCHANTED_EMERALD", 960d);
        npcSellPrices.put("ENCHANTED_EMERALD_BLOCK", 153600d);
        npcSellPrices.put("REDSTONE", 1d);
        npcSellPrices.put("ENCHANTED_REDSTONE", 160d);
        npcSellPrices.put("ENCHANTED_REDSTONE_BLOCK", 25600d);
        npcSellPrices.put("QUARTZ", 4d);
        npcSellPrices.put("ENCHANTED_QUARTZ", 640d);
        npcSellPrices.put("ENCHANTED_QUARTZ_BLOCK", 102400d);
        npcSellPrices.put("OBSIDIAN", 12d);
        npcSellPrices.put("ENCHANTED_OBSIDIAN", 1920d);
        npcSellPrices.put("GLOWSTONE_DUST", 2d);
        npcSellPrices.put("ENCHANTED_GLOWSTONE_DUST", 320d);
        npcSellPrices.put("ENCHANTED_GLOWSTONE", 61000d);
        npcSellPrices.put("GRAVEL", 3d);
        npcSellPrices.put("FLINT", 4d);
        npcSellPrices.put("ENCHANTED_FLINT", 640d);
        npcSellPrices.put("ICE", 0.5d);
        npcSellPrices.put("PACKED_ICE", 4.5d);
        npcSellPrices.put("ENCHANTED_ICE", 80d);
        npcSellPrices.put("ENCHANTED_PACKED_ICE", 12800d);
        npcSellPrices.put("NETHERRACK", 1d);
        npcSellPrices.put("SAND", 2d);
        npcSellPrices.put("ENCHANTED_SAND", 320d);
        npcSellPrices.put("ENDER_STONE", 2d);
        npcSellPrices.put("ENCHANTED_ENDSTONE", 320d);
        npcSellPrices.put("SNOW_BALL", 1d);
        npcSellPrices.put("SNOW_BLOCK", 4d);
        npcSellPrices.put("ENCHANTED_SNOW_BLOCK", 600d);
        npcSellPrices.put("ROTTEN_FLESH", 2d);
        npcSellPrices.put("ENCHANTED_ROTTEN_FLESH", 320d);
        npcSellPrices.put("BONE", 2d);
        npcSellPrices.put("ENCHANTED_BONE", 320d);
        npcSellPrices.put("ENCHANTED_BONE_BLOCK", 51200d);
        npcSellPrices.put("STRING", 3d);
        npcSellPrices.put("ENCHANTED_STRING", 480d);
        npcSellPrices.put("SPIDER_EYE", 3d);
        npcSellPrices.put("ENCHANTED_SPIDER_EYE", 480d);
        npcSellPrices.put("ENCHANTED_FERMENTED_SPIDER_EYE", 31000d);
        npcSellPrices.put("SULPHUR", 4d);
        npcSellPrices.put("ENCHANTED_GUNPOWDER", 640d);
        npcSellPrices.put("ENCHANTED_FIREWORK_ROCKET", 41000d);
        npcSellPrices.put("ENDER_PEARL", 10d);
        npcSellPrices.put("ENCHANTED_ENDER_PEARL", 200d);
        npcSellPrices.put("ENCHANTED_EYE_OF_ENDER", 3520d);
        npcSellPrices.put("GHAST_TEAR", 16d);
        npcSellPrices.put("ENCHANTED_GHAST_TEAR", 80d);
        npcSellPrices.put("SLIME_BALL", 5d);
        npcSellPrices.put("ENCHANTED_SLIME_BALL", 800d);
        npcSellPrices.put("ENCHANTED_SLIME_BLOCK", 128000d);
        npcSellPrices.put("BLAZE_ROD", 9d);
        npcSellPrices.put("ENCHANTED_BLAZE_POWDER", 1440d);
        npcSellPrices.put("ENCHANTED_BLAZE_ROD", 230400d);
        npcSellPrices.put("MAGMA_CREAM", 8d);
        npcSellPrices.put("ENCHANTED_MAGMA_CREAM", 1280d);
        npcSellPrices.put("LOG", 2d);
        npcSellPrices.put("ENCHANTED_OAK_LOG", 320d);
        npcSellPrices.put("LOG:1", 2d);
        npcSellPrices.put("ENCHANTED_SPRUCE_LOG", 320d);
        npcSellPrices.put("LOG:2", 2d);
        npcSellPrices.put("ENCHANTED_BIRCH_LOG", 320d);
        npcSellPrices.put("LOG_2:1", 2d);
        npcSellPrices.put("ENCHANTED_DARK_OAK_LOG", 320d);
        npcSellPrices.put("LOG_2", 2d);
        npcSellPrices.put("ENCHANTED_ACACIA_LOG", 320d);
        npcSellPrices.put("LOG:3", 2d);
        npcSellPrices.put("ENCHANTED_JUNGLE_LOG", 320d);
        npcSellPrices.put("RAW_FISH", 6d);
        npcSellPrices.put("ENCHANTED_RAW_FISH", 960d);
        npcSellPrices.put("ENCHANTED_COOKED_FISH", 153600d);
        npcSellPrices.put("RAW_FISH:1", 5d);
        npcSellPrices.put("ENCHANTED_RAW_SALMON", 800d);
        npcSellPrices.put("ENCHANTED_COOKED_SALMON", 128000d);
        npcSellPrices.put("RAW_FISH:2", 20d);
        npcSellPrices.put("ENCHANTED_CLOWNFISH", 3200d);
        npcSellPrices.put("RAW_FISH:3", 15d);
        npcSellPrices.put("ENCHANTED_PUFFERFISH", 2400d);
        npcSellPrices.put("PRISMARINE_SHARD", 5d);
        npcSellPrices.put("ENCHANTED_PRISMARINE_SHARD", 400d);
        npcSellPrices.put("PRISMARINE_CRYSTALS", 5d);
        npcSellPrices.put("ENCHANTED_PRISMARINE_CRYSTALS", 400d);
        npcSellPrices.put("CLAY_BALL", 3d);
        npcSellPrices.put("ENCHANTED_CLAY_BALL", 480d);
        npcSellPrices.put("WATER_LILY", 10d);
        npcSellPrices.put("ENCHANTED_WATER_LILY", 1600d);
        npcSellPrices.put("INK_SACK", 2d);
        npcSellPrices.put("ENCHANTED_INK_SACK", 160d);
        npcSellPrices.put("SPONGE", 50d);
        npcSellPrices.put("ENCHANTED_SPONGE", 2000d);
        npcSellPrices.put("ENCHANTED_WET_SPONGE", 80000d);
        npcSellPrices.put("CARROT_BAIT", 7d);
        npcSellPrices.put("MINNOW_BAIT", 12d);
        npcSellPrices.put("FISH_BAIT", 20d);
        npcSellPrices.put("LIGHT_BAIT", 16d);
        npcSellPrices.put("DARK_BAIT", 8d);
        npcSellPrices.put("SPOOKY_BAIT", 10d);
        npcSellPrices.put("SPIKED_BAIT", 20d);
        npcSellPrices.put("BLESSED_BAIT", 42d);
        npcSellPrices.put("ICE_BAIT", 3d);
        npcSellPrices.put("WHALE_BAIT", 80d);
        npcSellPrices.put("REVENANT_FLESH", 0d);
        npcSellPrices.put("REVENANT_VISCERA", 0d);
        npcSellPrices.put("TARANTULA_WEB", 0d);
        npcSellPrices.put("TARANTULA_SILK", 0d);
        npcSellPrices.put("WOLF_TOOTH", 0d);
        npcSellPrices.put("GOLDEN_TOOTH", 0d);
        npcSellPrices.put("HOT_POTATO_BOOK", 13000d);
        npcSellPrices.put("FUMING_POTATO_BOOK", 0d);
        npcSellPrices.put("COMPACTOR", 640d);
        npcSellPrices.put("SUPER_COMPACTOR_3000", 50000d);
        npcSellPrices.put("SUMMONING_EYE", 0d);
        npcSellPrices.put("PROTECTOR_FRAGMENT", 0d);
        npcSellPrices.put("OLD_FRAGMENT", 0d);
        npcSellPrices.put("UNSTABLE_FRAGMENT", 0d);
        npcSellPrices.put("STRONG_FRAGMENT", 0d);
        npcSellPrices.put("YOUNG_FRAGMENT", 0d);
        npcSellPrices.put("WISE_FRAGMENT", 0d);
        npcSellPrices.put("SUPERIOR_FRAGMENT", 0d);
        npcSellPrices.put("HOLY_FRAGMENT", 0d);
        npcSellPrices.put("ENCHANTED_REDSTONE_LAMP", 30720d);
        npcSellPrices.put("ENCHANTED_LAVA_BUCKET", 50000d);
        npcSellPrices.put("HAMSTER_WHEEL", 20000d);
        npcSellPrices.put("FOUL_FLESH", 25000d);
        npcSellPrices.put("CATALYST", 500d);
        npcSellPrices.put("GREEN_CANDY", 0d);
        npcSellPrices.put("PURPLE_CANDY", 0d);
        npcSellPrices.put("WHITE_GIFT", 0d);
        npcSellPrices.put("GREEN_GIFT", 0d);
        npcSellPrices.put("RED_GIFT", 0d);
        npcSellPrices.put("RECOMBOBULATOR_3000", 0d);
        npcSellPrices.put("STOCK_OF_STONKS", 0d);
    }
}
